import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    height: 60,
    // borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: '#F9C900',
  },
  header1: {
    height: 60,
    // borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: '#29abe2',
  },
  body: {
    height: 300,
    // flex: 1,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  inbody: {
    // borderWidth: 1,
    height: '60%',
    width: '100%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 50,
    backgroundColor: '#F9C900',
  },
  inbody1: {
    // borderWidth: 1,
    height: '70%',
    width: '100%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#29abe2',
  },
  image: {
    height: 50,
    width: 120,
    // borderWidth: 1,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  iconBank: {
    height: '100%',
    width: '100%',
  },
  Picker: {
    height: 50,
    width: 150,
    marginBottom: 20,
  },
  loading: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  pacTouchable: {
    height: 70,
    width: '100%',
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    // paddingHorizontal: 10,
  },
  bottom: {
    height: 10,
    // borderWidth: 1,
  },
  klik: {
    // borderWidth: 1,
    height: 50,
    width: '50%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9C900',
  },
  klik1: {
    // borderWidth: 1,
    height: 50,
    width: '80%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#29abe2',
  },
  textSend: {
    fontSize: 18,
    color: '#ffff',
    fontWeight: 'bold',
  },
  input: {
    height: 50,
    width: '70%',
    // borderWidth: 1,
    paddingLeft: 20,
    paddingRight: 30,
    borderRadius: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffff',
  },
  back: {
    height: 50,
    width: 50,
  },
  pactBack: {
    width: '100%',
    // borderWidth: 1,
    paddingLeft: 20,
    justifyContent: 'center',
    marginTop: 100,
  },
  klikBack: {
    height: 70,
    width: 50,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pactNominal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
  },
  pact: {
    height: 80,
    // borderWidth: 1,
    width: '85%',
    // backgroundColor: '#ffffff',
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 20,
    // borderBottomWidth: 1,
  },
  input1: {
    marginTop: 10,
    height: 70,
    width: '100%',
    borderRadius: 10,
    maxHeight: 90,
    marginBottom: 10,
    backgroundColor: '#ffffff',
    paddingLeft: 10,
  },
  text: {
    color: '#ffff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  backUp: {
    height: 25,
    width: 25,
    marginRight: 10,
  },
});

export {styles};
