import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    backgroundColor: '#29abe2',
    height: 60,
    alignItems: 'center',
    paddingHorizontal: 20,
    flexDirection: 'row',
  },
  title: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  icon: {
    height: 25,
    width: 25,
    marginRight: 10,
  },
  pactName: {
    // height: 30,
    // borderWidth: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    margin: 3,
    borderBottomWidth: 1,
    borderBottomColor: '#a9a9',
    paddingBottom: 2,
    marginBottom: 3,
  },
  data: {
    // borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 80,
    width: '100%',
    alignItems: 'center',
  },
  inData: {
    height: 70,
    width: '31%',
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#ffff',
    elevation: 6,
  },
  inbody: {
    // borderWidth: 1,
    margin: 10,
    height: 220,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#ffffff',
    elevation: 7,
  },
  inbody1: {
    // borderWidth: 1,
    margin: 10,
    height: 200,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#ffffff',
    elevation: 7,
  },
  text: {
    color: '#a9a9a9',
    fontWeight: 'bold',
    fontSize: 14,
  },
  textStock: {
    color: '#29abe2',
    fontSize: 14,
    fontWeight: 'bold',
  },
  date: {
    height: 80,
    borderBottomColor: '#29abe2',
    borderBottomWidth: 2,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inDate: {
    alignItems: 'center',
  },
  text1: {
    color: '#800000',
    marginBottom: 5,
    fontWeight: 'bold',
  },
  text2: {
    color: '#008000',
    marginBottom: 5,
    fontWeight: 'bold',
  },
  pactKlik: {
    height: 70,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
    backgroundColor: '#29abe2',
  },
  klik: {
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    height: 50,
    width: '100%',
    backgroundColor: '#ffffff',
  },
  textSend: {
    color: '#29abe2',
    fontSize: 20,
    fontWeight: 'bold',
  },
});

export {styles};
