import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffff',
  },
  header: {
    height: 60,
    // borderWidth: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#29abe2',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#ffffff',
  },
  body: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    // borderWidth: 1,
  },
  icon: {
    height: 25,
    width: 25,
    marginRight: 15,
  },
  inData: {
    height: 50,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  delete: {
    height: 50,
    width: 50,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 15,
  },
  inBody: {
    // borderWidth: 1,
    height: 150,
    width: '100%',
    marginVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    elevation: 9,
  },
  pactName: {
    flexDirection: 'row',
    // borderWidth: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textName: {
    color: '#a9a9',
    fontWeight: 'bold',
    fontSize: 15,
    marginRight: 10,
  },
  data: {
    height: 70,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  inHeader: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  icondelete: {
    height: 25,
    width: 25,
  },
  inItem: {
    // borderWidth: 1,
    height: 70,
    width: 75,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottom: {
    height: 65,
    // borderWidth: 1,
    paddingHorizontal: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#29abe2',
  },
  inBottom: {
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 50,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  textSend: {
    color: '#29abe2',
    fontWeight: 'bold',
    fontSize: 20,
  },
  Modal: {
    flex: 1,
  },
  topModal: {
    height: '55%',
    width: '100%',
    backgroundColor: '#a9a9',
    opacity: 0.5,
  },
  dataMoal: {
    height: 255,
    width: '100%',
    // alignItems: 'center',
    justifyContent: 'center',
    // borderWidth: 1,
    elevation: 9,
    backgroundColor: '#ffffff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  titleModal: {
    textAlign: 'center',
    marginBottom: 10,
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 20,
  },
  topDataModal: {
    // borderWidth: 1,
    height: '40%',
    justifyContent: 'center',
    paddingHorizontal: 50,
  },
  input: {
    borderBottomWidth: 2,
    borderBottomColor: '#a9a9',
    height: 50,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  iinput: {
    width: '90%',
    // borderWidth: 1,
  },
  pactklikModal: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    // borderWidth: 1,
    height: 100,
    width: '100%',
    justifyContent: 'center',
    marginTop: 15,
  },
  klikM: {
    // borderWidth: 1,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '30%',
    borderRadius: 10,
    backgroundColor: '#29abe2',
    marginHorizontal: 10,
  },
  klikM1: {
    // borderWidth: 1,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '30%',
    borderRadius: 10,
    backgroundColor: '#800000',
    marginHorizontal: 10,
  },
  klikM2: {
    // borderWidth: 1,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '30%',
    borderRadius: 10,
    backgroundColor: '#F9C900',
    marginHorizontal: 10,
  },
  textModal: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 20,
  },
  textAttention: {
    color: '#800000',
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 10,
  },
});

export {styles};
